# Generated by Django 5.2.12 on 2026-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
