# Generated by Django 5.2.12 on 2026-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_emergency_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_medicines',
            field=models.JSONField(default=list),
        ),
    ]
